name: Run Model

on:
  workflow_run:
    workflows: ["Train Model"]
    types:
      - completed

jobs:

  inference:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: train-pipline.yml
        name: trained-model

    - name: List model directory
      run: ls -l /

    - name: List downloaded artifact
      run: ls -l ${{ steps.download-artifact.outputs.repo-path }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull Docker image
      run: docker pull ghcr.io/levep/mymodel:latest

    - name: Run Docker container for inference
      run: |
        mkdir -p ./output
        docker run --name ml-inference -v ${{ github.workspace }}/${{ steps.download-artifact.outputs.repo-path }}:/app/models -v ${{ github.workspace }}/output:/app/output ghcr.io/levep/mymodel:latest python main.py --data_path /app/data/candy-data.csv --model_path /app/models/model.pkl --type Predict

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: model-output
        path: output/
